on:
  workflow_dispatch:
jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          node ../.github/actions-scripts/persist_octo.mjs
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
